---
# tasks file for users

- name: Set a list with username
  set_fact:
    username_list: "{{ users_present | map(attribute='name') | list }}"
  tags:
    - setup
    - users

- name: Create groups for users
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid | default(omit) }}"
    state: present
  with_items:
    - "{{ users_present }}"
  tags:
    - setup
    - users

- name: Create users
  user:
    name: "{{ item.name }}"
    group: "{{ item.name }}"
    groups: "{{ item.groups | join(',') if item.groups is defined else omit }}"
    shell: "{{ item.shell if item.shell is defined else '/bin/bash' }}"
    comment: "{{ item.comment | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
    createhome: "{{ item.createhome | default(true) }}"
    system: "{{ item.system | default(false) }}"
    password: "{{ item.password | default(omit) }}"
    state: present
  with_items:
    - "{{ users_present }}"
  tags:
    - setup
    - users

- name: Set SSH-Keys for users
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
    manage_dir: true
    state: present
  with_subelements:
    - "{{ users_present }}"
    - "ssh_keys"
    - flags:
        skip_missing: true
  tags:
    - setup
    - users

- name: Set the user home to secure
  when: item.securehome | default(false)
  file:
    path: "{{ item.home if item.home is defined else '/home/' + item.name }}"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0700
  with_items:
    - "{{ users_present }}"
  tags:
    - setup
    - users

- name: Set absent non system users - but does not remove
  user:
    name: "{{ item }}"
    state: absent
    remove: false
  with_items:
    - "{{ users_absent }}"
  tags:
    - setup
    - users
