---

- hosts: all

  vars:

    users_present:
      - name: foo
        uid: 5024
        gid: 5024
        groups:
          - foo_group
          - second_foo_group
        password: "$6$rounds=656000$RF0sdfsfsdfsdfsdfsdfVpiF6j2XVk00/FfYg0X.qhP1ZuZld/4qmTz/GvCUTWScZf37rDK70R530"
        shell: /bin/bash
        ssh_keys:
          # yamllint disable-line rule:line-length
          - 'ssh-rsa AAAAB3NzaC1ysdfsdfsdfsdfsdfsdfEhN+XSeIc2to9ZCNPM3w/JlkR2tnLpCOJvpPwXpbG3RJUrXN1IzTIlUvKryH0WfH1jq7UzBPy6JnPzLFAox5f6z+Ee0F32kswvYsec7e+C8f4ofGS9EZK9FW5PZdXT6mF0hzdc/wCT5kR2mzZB5hE1up8iNPlof58UEMHFNLNle2NbAvUAoYoi3quO0f388BWwDp7QzzzG2Ex1T19bRFzTKdnpCUUKs+wfQItRVwOCkH5amrfQceqr5LBfWZLcVC92mmh43572m3d7e5E1p3n5jsfHOiUqrqbnrBePFATl6sEIz7Pm4LBO+g4I6UDVvIOB0MbnijcCK6uPENyll2qpXGLtA7TMKjWuFPZtXN79xovQbaLk2WdYMCfUEFZwt+lOyZsWfOeW9VVJwt+g5mYZUGGiqLgqloHUXTMliqTlJviSjp+PGIsEbBN7Nc/pQ92S8OWp8oY0lMFwbuAmepuBS6loLpX1D25iaZBLv5waL0R2srtBdx+hvhTtCNYB0mx7513BIElwKPc/BzPMkrXhnKsJs+x5428VxQ4EhNhfIGOOs4dLBaoqLJEYe6+5zzFMWa91qScINyUVygfpzjMDmydZJ3njno+F9sY9Ajl90dQQnoMUSlZJaaun9jLffpjz+AQlZ8bShaDNilrgQ== foo@bar.com'

      - name: bar
        comment: bar service user
        shell: "/bin/sh"
        home: "/opt/bar"
        createhome: false

      - name: baz
        comment: baz user
        uid: 503
        system: true

      - name: baaz
        comment: baaz
        uid: 6025
        ssh_keys:
          # yamllint disable-line rule:line-length
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEcwXInrCMq06ibBMNl/VkHN3pAeqFiLg9XKht0ekH+qjaJLoWcgsV3Qqu6+Nasdasdasasdasgsdfgdfgsdfgsdfgsdfg/JS8p2zAraDpBxh/8NFLztwRYS8hFZ4p49x4zA8Jz4+xLIa+uA5vMtqQk1Le2AtaUFP/DfAMEI317GGVb396w6wr9Z7SH6d+HkQJy5E2EA84btI9DpRXzh0zL2T+SyIM/YzZfG4ehB6gf9ZijHr/ir9djYiVF sdf
          # yamllint disable-line rule:line-length
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8q9blZ+M5cjgHJv9lIZnWsVXFxm1BGOD8zwkw/GTPhomNxIcI10UPX17eQJ8asdasdasasdasgsdfgdfgsdfgsdfgsdfg/uQiYjoKWJhQXZSeGK+Im9NmGksGwNrtx13yPRTVnabVtDpg48UTOTNIUFMXtX9TJOs3fgRsClDWdH4htLZVYngb99O8ZK6HxijA/1U1tqejKO+OKyiOxaP3eUZ30nILCN+fiuVP2oNOT5XD5huVD/IVdyblXiOtIb2K/5Oad3KbojVJ7mFcB5AOddSCqspEJz5NFe0jdhyEOlZn/k5DwOllXaq/nuBg3dKFsG9iO2sjKYr sdf
        securehome: true

      - name: quux
        comment: quux service user
        shell: "/bin/sh"
        home: "/opt/quux"
        securehome: true

  pre_tasks:

    - name: Create user groups
      group:
        name: "{{ item }}"
        state: present
      with_items:
        - foo_group
        - second_foo_group

  roles:
    - role: users
